connector.name=mysql
connection-url=jdbc:mysql://mysql-1a212797-sakthid282004-968d.l.aivencloud.com:14559/defaultdb?sslMode=REQUIRED
connection-user=avnadmin
connection-password=AVNS_Bea67ALMK_hYrl718cx
