connector.name=postgresql
connection-url=jdbc:postgresql://dpg-daah8kon74is73av2rpg-a.singapore-postgres.render.com:5432/dev_trino?sslmode=require
connection-user=dev_trino_user
connection-password=NafnYi2RKXolkEh8hjtN53d6g16dQo7w
